compatibility_date = "2021-11-25"

type = "javascript"
name = "mealcal"
account_id = "c3b373ae8a90a6494e520f962bdf462b"
workers_dev = true
zone_id = "7ae87e4d893d4acb2a81ead11628a9cb"

[site]
entry-point = "./"
bucket = "./dist/static"

[build]
command = "npm run build:nocleanup"

[build.upload]
format = "modules"
main = "index.mjs"